version: "3"
services:
    redis:
        image: redis:5.0.0-alpine
        restart: always
        container_name: myapp-redis
        ports:
            - 6379:6379
        networks:
             myapp_net: 
                 ipv4_address: 172.16.238.13
   
    db:
        image: mysql:5.7.22
        restart: always
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: iglprjj
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3306:3306"
        networks:
            myapp_net:
                ipv4_address: 172.16.238.11
    app:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: myapp-web

        depends_on:
            - db
            - redis
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/myapp
        networks:
            myapp_net:
                ipv4_address: 172.16.238.12
volumes:
    web-app:
        driver: local
networks:
    myapp_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/18
    
 